import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        Date: 'readonly',
        Math: 'readonly',
        JSON: 'readonly',
        RegExp: 'readonly',
        URL: 'readonly',
        FormData: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        XMLHttpRequest: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        Headers: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        Image: 'readonly',
        Audio: 'readonly',
        Video: 'readonly',
        confirm: 'readonly',
        alert: 'readonly',
        prompt: 'readonly',
        close: 'readonly',
        open: 'readonly',
        print: 'readonly',
        location: 'readonly',
        history: 'readonly',
        crypto: 'readonly',
        indexedDB: 'readonly',
        caches: 'readonly',
        ServiceWorkerRegistration: 'readonly',
        matchMedia: 'readonly',
        visualViewport: 'readonly',
        getComputedStyle: 'readonly',
        TextEncoder: 'readonly',
        // Third-party libs
        Swal: 'readonly',
        html2canvas: 'readonly',
        jspdf: 'readonly',
        html2pdf: 'readonly',
        // Supabase init
        _FB_READY: 'writable',
        _supabase: 'writable',
        _nuraInit: 'writable',
        // db.js exports
        DB: 'writable',
        notifyUpdate: 'writable',
        getLastUpdateStr: 'writable',
        syncUI: 'writable',
        pulseSyncDot: 'writable',
        fbSave: 'writable',
        fbRemove: 'writable',
        fbSaveMany: 'writable',
        fbDescontarStock: 'writable',
        COLS_LIST: 'writable',
        cargarColeccion: 'writable',
        // ui.js exports
        genId: 'writable',
        fmt: 'writable',
        fmtL: 'writable',
        fmtDate: 'writable',
        escapeHTML: 'writable',
        hashPassword: 'writable',
        swalConfirm: 'writable',
        swalError: 'writable',
        swalSuccess: 'writable',
        swalInfo: 'writable',
        toast: 'writable',
        CATEGORIAS: 'writable',
        EMOJIS_CAT: 'writable',
        PRES_RAPIDAS: 'writable',
        openModal: 'writable',
        closeModal: 'writable',
        currentPage: 'writable',
        PAGES_ADMIN: 'writable',
        PAGES_VENDEDOR: 'writable',
        buildMenu: 'writable',
        navigate: 'writable',
        renderPage: 'writable',
        moneyInput: 'writable',
        unitInput: 'writable',
        // auth.js exports
        Sesion: 'writable',
        setupLogin: 'writable',
        renderUsuarios: 'writable',
        // productos.js exports
        renderCatalogo: 'writable',
        recalcTodasPres: 'writable',
        recalcPres: 'writable',
        calcAccesorio: 'writable',
        openProductDetail: 'writable',
        // clientes.js exports
        renderClientes: 'writable',
        // ventas.js exports
        renderVentas: 'writable',
        buildVendibles: 'writable',
        updateVentaTotals: 'writable',
        renderPendientes: 'writable',
        // compras.js exports
        renderCompras: 'writable',
        calcCompra: 'writable',
        onCpProdChange: 'writable',
        // stock.js exports
        renderStock: 'writable',
        renderNuevoStock: 'writable',
        // combos.js exports
        renderCombos: 'writable',
        // deudas.js exports
        renderDeudas: 'writable',
        renderDeudasPendientes: 'writable',
        renderDeudasCliente: 'writable',
        // reportes.js exports
        renderDashboard: 'writable',
        renderReportes: 'writable',
        renderMisReportes: 'writable',
        renderAjustes: 'writable',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_|^e$' }],
      'no-undef': 'error',
      'no-redeclare': 'off',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-unreachable': 'warn',
      'no-constant-condition': 'warn',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-extra-semi': 'warn',
      'no-func-assign': 'error',
      'no-inner-declarations': 'warn',
      'use-isnan': 'error',
      'valid-typeof': 'error',
    },
  },
  {
    ignores: ['node_modules/', '*.min.js', 'env.js', 'sw.js', 'eslint.config.js'],
  },
];
