services:
  - type: web
    name: los10000-macko
    runtime: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 3000
    disk:
      name: database
      mountPath: /database
      sizeGB: 1
