services:
  - type: web
    name: los10000-macko
    runtime: node
    buildCommand: npm install
    startCommand: node backend/server.js
    disk:
      name: db
      mountPath: /app/database
      sizeGB: 1
